In [1]:
!pip install scikit-learn
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn

In [62]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import tensorflow as tf

In [64]:
data = pd.read_csv("https://gist.githubusercontent.com/jaidevd/23aef12e9bf56c618c41/raw/c05e98672b8d52fa0cb94aad80f75eb78342e5d4/books_new.csv")
df= pd.DataFrame(data)
df.head()


Title            Author       Genre           SubGenre  \
0  Fundamentals of Wavelets  Goswami, Jaideva        tech  signal_processing   
1                Data Smart     Foreman, John        tech       data_science   
2  God Created the Integers  Hawking, Stephen        tech        mathematics   
3         Superfreakonomics   Dubner, Stephen     science          economics   
4               Orientalism      Said, Edward  nonfiction            history   

   Height      Publisher  
0     228          Wiley  
1     235          Wiley  
2     197        Penguin  
3     179  HarperCollins  
4     197        Penguin

In [65]:
df['Author'] = df['Author'].str.replace(',', '')
df['Author'] = df['Author'].str.replace(' ', '')
df['SubGenre'] = df['SubGenre'].str.replace('_', '')
print(df)


                            Title            Author       Genre  \
0        Fundamentals of Wavelets    GoswamiJaideva        tech   
1                      Data Smart       ForemanJohn        tech   
2        God Created the Integers    HawkingStephen        tech   
3               Superfreakonomics     DubnerStephen     science   
4                     Orientalism        SaidEdward  nonfiction   
..                            ...               ...         ...   
206      Structure and Randomness        TaoTerence     science   
207  Image Processing with MATLAB       EddinsSteve        tech   
208                   Animal Farm      OrwellGeorge     fiction   
209                    Idiot, The  DostoevskyFyodor     fiction   
210            Christmas Carol, A    DickensCharles     fiction   

             SubGenre  Height      Publisher  
0    signalprocessing     228          Wiley  
1         datascience     235          Wiley  
2         mathematics     197        Penguin  
3      

In [66]:
df['Publisher'].fillna("", inplace=True)
df['Author'].fillna("", inplace=True)
print(df)

                            Title            Author       Genre  \
0        Fundamentals of Wavelets    GoswamiJaideva        tech   
1                      Data Smart       ForemanJohn        tech   
2        God Created the Integers    HawkingStephen        tech   
3               Superfreakonomics     DubnerStephen     science   
4                     Orientalism        SaidEdward  nonfiction   
..                            ...               ...         ...   
206      Structure and Randomness        TaoTerence     science   
207  Image Processing with MATLAB       EddinsSteve        tech   
208                   Animal Farm      OrwellGeorge     fiction   
209                    Idiot, The  DostoevskyFyodor     fiction   
210            Christmas Carol, A    DickensCharles     fiction   

             SubGenre  Height      Publisher  
0    signalprocessing     228          Wiley  
1         datascience     235          Wiley  
2         mathematics     197        Penguin  
3      

In [67]:
df['Author']=df['Author']+" "+df['Genre']+" "+df['SubGenre']+" "+df['Publisher']
print(df)
df['Author']

                            Title  \
0        Fundamentals of Wavelets   
1                      Data Smart   
2        God Created the Integers   
3               Superfreakonomics   
4                     Orientalism   
..                            ...   
206      Structure and Randomness   
207  Image Processing with MATLAB   
208                   Animal Farm   
209                    Idiot, The   
210            Christmas Carol, A   

                                            Author       Genre  \
0       GoswamiJaideva tech signalprocessing Wiley        tech   
1               ForemanJohn tech datascience Wiley        tech   
2          HawkingStephen tech mathematics Penguin        tech   
3    DubnerStephen science economics HarperCollins     science   
4            SaidEdward nonfiction history Penguin  nonfiction   
..                                             ...         ...   
206                TaoTerence science mathematics      science   
207             EddinsSteve

0         GoswamiJaideva tech signalprocessing Wiley
1                 ForemanJohn tech datascience Wiley
2            HawkingStephen tech mathematics Penguin
3      DubnerStephen science economics HarperCollins
4              SaidEdward nonfiction history Penguin
                           ...                      
206                  TaoTerence science mathematics 
207               EddinsSteve tech signalprocessing 
208                    OrwellGeorge fiction classic 
209                DostoevskyFyodor fiction classic 
210                  DickensCharles fiction classic 
Name: Author, Length: 211, dtype: object

In [68]:
new_df= df[['Title','Author']]
print(new_df)

                            Title  \
0        Fundamentals of Wavelets   
1                      Data Smart   
2        God Created the Integers   
3               Superfreakonomics   
4                     Orientalism   
..                            ...   
206      Structure and Randomness   
207  Image Processing with MATLAB   
208                   Animal Farm   
209                    Idiot, The   
210            Christmas Carol, A   

                                            Author  
0       GoswamiJaideva tech signalprocessing Wiley  
1               ForemanJohn tech datascience Wiley  
2          HawkingStephen tech mathematics Penguin  
3    DubnerStephen science economics HarperCollins  
4            SaidEdward nonfiction history Penguin  
..                                             ...  
206                TaoTerence science mathematics   
207             EddinsSteve tech signalprocessing   
208                  OrwellGeorge fiction classic   
209              Dostoevs

In [54]:
new_df['Author'][0]

'GoswamiJaideva tech signalprocessing Wiley'

In [73]:
new_df.loc[:,'Author']=new_df['Author'].apply(lambda x:x.lower())
print(new_df)

                            Title  \
0        Fundamentals of Wavelets   
1                      Data Smart   
2        God Created the Integers   
3               Superfreakonomics   
4                     Orientalism   
..                            ...   
206      Structure and Randomness   
207  Image Processing with MATLAB   
208                   Animal Farm   
209                    Idiot, The   
210            Christmas Carol, A   

                                            Author  
0       goswamijaideva tech signalprocessing wiley  
1               foremanjohn tech datascience wiley  
2          hawkingstephen tech mathematics penguin  
3    dubnerstephen science economics harpercollins  
4            saidedward nonfiction history penguin  
..                                             ...  
206                taoterence science mathematics   
207             eddinssteve tech signalprocessing   
208                  orwellgeorge fiction classic   
209              dostoevs

In [78]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

new_df['Author'].apply(stem)

0       goswamijaideva tech signalprocess wiley
1                foremanjohn tech datasci wiley
2          hawkingstephen tech mathemat penguin
3      dubnerstephen scienc econom harpercollin
4            saidedward nonfict histori penguin
                         ...                   
206                      taoter scienc mathemat
207               eddinsstev tech signalprocess
208                 orwellgeorg fiction classic
209            dostoevskyfyodor fiction classic
210                dickenscharl fiction classic
Name: Author, Length: 211, dtype: object

In [79]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=10000,stop_words='english')
vector = cv.fit_transform(new_df['Author']).toarray()
print(vector)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [80]:
vector[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [82]:
cv.get_feature_names_out()

array(['ackroydpeter', 'aczelamir', 'anthology', 'apress',
       'archerjeffery', 'autobiography', 'bachrichard', 'baz', 'bbc',
       'bellet', 'blackswan', 'bodanisdavid', 'bodley', 'bradskygary',
       'braithwaite', 'browndan', 'camusalbert', 'caprafritjof',
       'classic', 'comic', 'computerscience', 'conwaydrew', 'corbettjim',
       'cormenthomas', 'crc', 'crichtonmichael', 'dalrymplewilliam',
       'datascience', 'dawkinsrichard', 'debsiddhartha', 'dell',
       'deshpandepl', 'deshpandesunita', 'devlinkeith', 'dickenscharles',
       'dickinsonpeter', 'dostoevskyfyodor', 'downeyallen',
       'doylearthurconan', 'druckerpeter', 'dubnerstephen', 'dudahart',
       'durantwill', 'durrellgerald', 'dylanbob', 'economics',
       'eddinssteve', 'education', 'elsevier', 'eralyabraham',
       'feynmanrichard', 'fiction', 'fiskrobert', 'follettken', 'fontana',
       'foremanjohn', 'forsythdavid', 'forsythfrederick', 'francosergio',
       'freepress', 'friedmanthomas', 'gardner

In [83]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)
print(similarity)

[[1.         0.5        0.25       ... 0.         0.         0.        ]
 [0.5        1.         0.25       ... 0.         0.         0.        ]
 [0.25       0.25       1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.66666667 0.66666667]
 [0.         0.         0.         ... 0.66666667 1.         0.66666667]
 [0.         0.         0.         ... 0.66666667 0.66666667 1.        ]]


In [84]:
def recommend(book):
    index = new_df[new_df['Title'] == book].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new_df.iloc[i[0]].Title)

In [88]:
recommend('Animal Farm')

World's Greatest Short Stories, The
Phantom of Manhattan, The
Selected Short Stories
Moon and Sixpence, The
Grapes of Wrath, The


In [91]:
pickle.dump(new_df,open('book_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [90]:
import pickle